---
- name: web
  hosts: all
  become: true
  #ignore_errors: yes
  tasks:
  
    - name: Remove old filesin a directory
      shell : rm -rf /var/lib/jenkins/workspace/httpd/*
      
    - name: Remove old containers
      shell: docker rm -f $(docker ps -qa)
      
    - name: Remove old images
      shell: docker rmi $(docker image ls -q)
      
    - name: Running compose files
      shell: docker-compose up -d 